const exampleLabels = [
  { text: "First Name", value: "firstName" },
  { text: "Last Name", value: "lastName" },
  { text: "Start Date", value: "startDate" },
  { text: "Department", value: "department" },
  { text: "Date of Birth", value: "dateOfBirth" },
  { text: "Street", value: "street" },
  { text: "City", value: "city" },
  { text: "State", value: "state" },
  { text: "Zip Code", value: "zipCode" },
];

const exampleData = [
  {
    firstName: "John",
    lastName: "Doe",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "01/01/1990",
    street: "Main Street",
    city: "NY",
    state: "AL",
    zipCode: "01800",
  },
  {
    firstName: "Elisa",
    lastName: "Tyrel",
    startDate: "03/02/2020",
    department: "Marketing",
    dateOfBirth: "01/25/1988",
    street: "Helia Street",
    city: "San Francisco",
    state: "AK",
    zipCode: "85699",
  },
  {
    firstName: "Roland",
    lastName: "Smith",
    startDate: "12/20/2020",
    department: "Sales",
    dateOfBirth: "01/16/1978",
    street: "Cross Street",
    city: "Irvine",
    state: "BK",
    zipCode: "78965",
  },
  {
    firstName: "Laetitia",
    lastName: "Menirel",
    startDate: "11/03/2014",
    department: "Engineering",
    dateOfBirth: "08/24/1985",
    street: "High Street",
    city: "Chicago",
    state: "UJ",
    zipCode: "87120",
  },
  {
    firstName: "Roman",
    lastName: "Pelio",
    startDate: "01/28/2018",
    department: "Human Resources",
    dateOfBirth: "05/22/1990",
    street: "Sea Street",
    city: "Seattle",
    state: "SG",
    zipCode: "99852",
  },
  {
    firstName: "Kristen",
    lastName: "Bird",
    startDate: "09/20/2012",
    department: "Marketing",
    dateOfBirth: "03/15/1975",
    street: "Side Street",
    city: "Boston",
    state: "VL",
    zipCode: "20369",
  },
  {
    firstName: "Nico",
    lastName: "Smith",
    startDate: "02/02/2017",
    department: "Legal",
    dateOfBirth: "03/29/1987",
    street: "Round Street",
    city: "Detroit",
    state: "DP",
    zipCode: "36124",
  },
  {
    firstName: "Lea",
    lastName: "Regan",
    startDate: "10/08/2015",
    department: "Engineering",
    dateOfBirth: "09/25/1979",
    street: "End Street",
    city: "Baltimore",
    state: "PI",
    zipCode: "79582",
  },
  {
    firstName: "Tim",
    lastName: "Legol",
    startDate: "02/13/2021",
    department: "Marketing",
    dateOfBirth: "10/05/1995",
    street: "Holy Street",
    city: "Dallas",
    state: "CM",
    zipCode: "25001",
  },
  {
    firstName: "Celia",
    lastName: "Hugh",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "06/14/1992",
    street: "Low Street",
    city: "Austin",
    state: "HY",
    zipCode: "97312",
  },
  {
    firstName: "John",
    lastName: "Doe",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "01/01/1990",
    street: "Main Street",
    city: "NY",
    state: "AL",
    zipCode: "01800",
  },
  {
    firstName: "Elisa",
    lastName: "Tyrel",
    startDate: "03/02/2020",
    department: "Marketing",
    dateOfBirth: "01/25/1988",
    street: "Helia Street",
    city: "San Francisco",
    state: "AK",
    zipCode: "85699",
  },
  {
    firstName: "Roland",
    lastName: "Smith",
    startDate: "12/20/2020",
    department: "Sales",
    dateOfBirth: "01/16/1978",
    street: "Cross Street",
    city: "Irvine",
    state: "BK",
    zipCode: "78965",
  },
  {
    firstName: "Laetitia",
    lastName: "Menirel",
    startDate: "11/03/2014",
    department: "Engineering",
    dateOfBirth: "08/24/1985",
    street: "High Street",
    city: "Chicago",
    state: "UJ",
    zipCode: "87120",
  },
  {
    firstName: "Roman",
    lastName: "Pelio",
    startDate: "01/28/2018",
    department: "Human Resources",
    dateOfBirth: "05/22/1990",
    street: "Sea Street",
    city: "Seattle",
    state: "SG",
    zipCode: "99852",
  },
  {
    firstName: "Kristen",
    lastName: "Bird",
    startDate: "09/20/2012",
    department: "Marketing",
    dateOfBirth: "03/15/1975",
    street: "Side Street",
    city: "Boston",
    state: "VL",
    zipCode: "20369",
  },
  {
    firstName: "Nico",
    lastName: "Smith",
    startDate: "02/02/2017",
    department: "Legal",
    dateOfBirth: "03/29/1987",
    street: "Round Street",
    city: "Detroit",
    state: "DP",
    zipCode: "36124",
  },
  {
    firstName: "Lea",
    lastName: "Regan",
    startDate: "10/08/2015",
    department: "Engineering",
    dateOfBirth: "09/25/1979",
    street: "End Street",
    city: "Baltimore",
    state: "PI",
    zipCode: "79582",
  },
  {
    firstName: "Tim",
    lastName: "Legol",
    startDate: "02/13/2021",
    department: "Marketing",
    dateOfBirth: "10/05/1995",
    street: "Holy Street",
    city: "Dallas",
    state: "CM",
    zipCode: "25001",
  },
  {
    firstName: "Celia",
    lastName: "Hugh",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "06/14/1992",
    street: "Low Street",
    city: "Austin",
    state: "HY",
    zipCode: "97312",
  },
];

let exampleLoopData = [];
for (let i = 0; i < 56; i++) {
  exampleLoopData.push({
    firstName: `Lea ${i}`,
    lastName: "Regan",
    startDate: "10/08/2015",
    department: "Engineering",
    dateOfBirth: "09/25/1979",
    street: "End Street",
    city: "Baltimore",
    state: "PI",
    zipCode: "79582",
  });
}

export { exampleLabels, exampleData, exampleLoopData };
